services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${SPRING_ELASTICSEARCH_PASSWORD}
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock: { soft: -1, hard: -1 }
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esplugins:/usr/share/elasticsearch/plugins
    ports:
      - "9200:9200"
    command:
      - bash
      - -c
      - |
        if [ ! -d "/usr/share/elasticsearch/plugins/analysis-nori" ]; then
          bin/elasticsearch-plugin install --batch analysis-nori;
        fi
        exec bin/elasticsearch
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2
    command: ["redis-server","--appendonly","yes","--requirepass","${SPRING_DATA_REDIS_PASSWORD}"]
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  esdata:
  esplugins:
  redisdata: