name: Build and deploy JAR app to Azure Web App - everyconti-product-server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew || true

      - name: Build with Gradle (bootJar)
        run: ./gradlew clean bootJar -x test

      - name: Show build outputs (debug)
        run: ls -la build/libs

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_84B91C0844024597BC07D74E239C6312 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9A92752F78DF49E09103E1A4F4188B61 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_217F3D460EEA4C8EAF7609BF7C4AAA7F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'everyconti-product-server'
          slot-name: 'Production'
          package: 'build/libs/*SNAPSHOT.jar'
